-- =============================================================================
-- Bob's Used Books workshop - Db2 LUW schema V2
-- Converted from 02_schema_oracle_v2.sql
-- =============================================================================
-- Listings model (no OFFERS table): BOOKS holds metadata only, LISTINGS holds
-- price / quantity / condition. 14 tables.
--
-- NOTE ON SCOPE: this is the *workshop demo* schema generation. It is NOT the
-- schema the bundled Spring Boot app validates against -- the app expects
-- BOOKS.NAME (not TITLE), an OFFERS table, and PRICE/QUANTITY inline on BOOKS.
-- See ../JavaBobsUsedBooks-Db2/src/main/resources/db/db2/02_schema_db2.sql for
-- the application schema. Do not load both into the same schema.
--
-- TYPE MAPPING APPLIED THROUGHOUT
--   NUMBER(19,0)          -> BIGINT
--   NUMBER(10,0)          -> INTEGER
--   NUMBER(38,2)          -> DECIMAL(31,2)   <-- Db2's maximum precision is 31,
--                                                not 38. Values above 10^29 in
--                                                a price/total would now
--                                                overflow. Harmless for this
--                                                data set; flagged because it
--                                                is a real narrowing.
--   NUMBER(1,0) + CHECK   -> SMALLINT + CHECK    (Db2 has no NUMBER(1); this is
--                                                also what Hibernate maps
--                                                Boolean to)
--   VARCHAR2(n CHAR)      -> VARCHAR(n)          (see CHAR SEMANTICS below)
--   VARCHAR2(n)           -> VARCHAR(n)
--   TIMESTAMP(6)          -> TIMESTAMP(6)
--   DATE                  -> DATE            <-- Oracle DATE carries a time
--                                                component; Db2 DATE does not.
--                                                Any time-of-day previously
--                                                stored in SHIPPED_DATE /
--                                                DELIVERED_DATE / CANCELLED_DATE
--                                                / PUBLISH_DATE / DATE_OF_BIRTH
--                                                is silently truncated.
--   BLOB                  -> BLOB            <-- Db2 BLOB requires an explicit
--                                                maximum length; 10M is used.
--   GENERATED BY DEFAULT AS IDENTITY -> same (Db2 supports this verbatim, and
--                                       BY DEFAULT is required because the seed
--                                       data inserts explicit ID values)
--
-- CHAR SEMANTICS: Oracle VARCHAR2(255 CHAR) is 255 *characters*. Db2
-- VARCHAR(255) is 255 *bytes*. For multi-byte (non-ASCII) content use
-- VARCHAR(255 CODEUNITS32), which reserves 255 characters at the cost of 4x
-- byte width. Left as bytes here because the demo data is ASCII; switch to
-- CODEUNITS32 if real user-generated content will be loaded.
--
-- ORACLE NOISE REMOVED: ENABLE, USING INDEX, NOORDER, NOKEEP, NOSCALE,
-- CACHE 20 -- no Db2 analogue or not meaningful.
--
-- Run as DEMO:  db2 -tvf 02_schema_db2_v2.sql
-- =============================================================================

CONNECT TO BOBSDB USER DEMO USING <DEMO_PASSWORD>;

-- Oracle: ALTER SESSION SET CURRENT_SCHEMA=demo
SET CURRENT SCHEMA DEMO;
SET PATH = SYSIBM, SYSFUN, SYSPROC, SYSIBMADM, DEMO;

-- =============================================================================
-- REFERENCE DATA TABLES
-- =============================================================================

CREATE TABLE BOOK_TYPES (
    ID           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CREATED_ON   TIMESTAMP(6),
    DESCRIPTION  VARCHAR(255),
    NAME         VARCHAR(255) NOT NULL,
    UPDATED_ON   TIMESTAMP(6),
    PRIMARY KEY (ID)
) IN DEMOTBS;

CREATE TABLE CONDITIONS (
    ID           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CREATED_ON   TIMESTAMP(6),
    DESCRIPTION  VARCHAR(255),
    NAME         VARCHAR(255) NOT NULL,
    UPDATED_ON   TIMESTAMP(6),
    PRIMARY KEY (ID)
) IN DEMOTBS;

CREATE TABLE GENRES (
    ID           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CREATED_ON   TIMESTAMP(6),
    DESCRIPTION  VARCHAR(255),
    NAME         VARCHAR(255) NOT NULL,
    UPDATED_ON   TIMESTAMP(6),
    PRIMARY KEY (ID)
) IN DEMOTBS;

CREATE TABLE PUBLISHERS (
    ID           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CREATED_ON   TIMESTAMP(6),
    DESCRIPTION  VARCHAR(255),
    NAME         VARCHAR(255) NOT NULL,
    UPDATED_ON   TIMESTAMP(6),
    WEBSITE      VARCHAR(255),
    PRIMARY KEY (ID)
) IN DEMOTBS;

-- =============================================================================
-- BOOKS (metadata only -- inventory lives in LISTINGS)
-- =============================================================================
-- YEAR was NUMBER(10,0). "YEAR" is a Db2 built-in scalar function name but is
-- NOT a reserved word, so it is legal as a column name unqualified. It is left
-- as YEAR to keep the column contract identical to Oracle.

CREATE TABLE BOOKS (
    ID            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    TITLE         VARCHAR(255),
    AUTHOR        VARCHAR(255),
    ISBN          VARCHAR(255),
    DESCRIPTION   VARCHAR(1000),
    PUBLISH_DATE  DATE,
    YEAR          INTEGER,
    CREATED_ON    TIMESTAMP(6),
    UPDATED_ON    TIMESTAMP(6),
    CREATED_BY    VARCHAR(255),
    GENRE_ID      BIGINT,
    PUBLISHER_ID  BIGINT,
    BOOK_TYPE_ID  BIGINT,
    SEARCH_TEXT   VARCHAR(1000),
    PRIMARY KEY (ID),
    CONSTRAINT FK_BOOKS_BOOK_TYPE FOREIGN KEY (BOOK_TYPE_ID) REFERENCES BOOK_TYPES (ID),
    CONSTRAINT FK_BOOKS_GENRE     FOREIGN KEY (GENRE_ID)     REFERENCES GENRES (ID),
    CONSTRAINT FK_BOOKS_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID)
) IN DEMOTBS;

-- =============================================================================
-- BOOKS_COVER (BLOB storage)
-- =============================================================================
-- Oracle "BLOB" is unbounded (4 GB). Db2 requires an explicit maximum length,
-- defaulting to 1 MB if omitted -- too small: the largest seeded cover is
-- ~120 KB, but 10M gives room for real cover art.
--
-- NOT LOGGED reduces log pressure for large LOBs but makes the column
-- non-recoverable by rollforward; left logged (the default) for safety.
-- Add COMPACT if storage matters more than read speed.

CREATE TABLE BOOKS_COVER (
    BOOK_ID       BIGINT NOT NULL,
    COVER_IMAGE   BLOB(10M),
    CONTENT_TYPE  VARCHAR(100),
    FILE_NAME     VARCHAR(255),
    CREATED_ON    TIMESTAMP(6),
    UPDATED_ON    TIMESTAMP(6),
    PRIMARY KEY (BOOK_ID),
    CONSTRAINT FK_BOOKS_COVER_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE
) IN DEMOTBS;

-- =============================================================================
-- CUSTOMERS
-- =============================================================================
-- Oracle's anonymous CHECK constraints are named here; Db2 auto-generates
-- opaque names otherwise, which makes later ALTER/DROP awkward.
-- ROLE is not reserved in Db2 (CREATE ROLE is a statement, not a keyword
-- restriction on identifiers), so the column name is kept.

CREATE TABLE CUSTOMERS (
    ID                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    USERNAME            VARCHAR(255),
    EMAIL               VARCHAR(255),
    FIRST_NAME          VARCHAR(255),
    LAST_NAME           VARCHAR(255),
    PHONE_NUMBER        VARCHAR(255),
    PASSWORD_HASH       VARCHAR(255),
    SUB                 VARCHAR(255),
    DATE_OF_BIRTH       DATE,
    CREATED_ON          TIMESTAMP(6),
    EMAIL_VERIFIED      SMALLINT DEFAULT 0,
    ROLE                VARCHAR(255),
    ACCOUNT_EXPIRED     SMALLINT DEFAULT 0,
    CREDENTIALS_EXPIRED SMALLINT DEFAULT 0,
    ACCOUNT_LOCKED      SMALLINT DEFAULT 0,
    LAST_LOGIN          TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT CK_CUST_ACCT_EXPIRED  CHECK (ACCOUNT_EXPIRED     IN (0,1)),
    CONSTRAINT CK_CUST_ACCT_LOCKED   CHECK (ACCOUNT_LOCKED      IN (0,1)),
    CONSTRAINT CK_CUST_CRED_EXPIRED  CHECK (CREDENTIALS_EXPIRED IN (0,1)),
    CONSTRAINT CK_CUST_EMAIL_VERIF   CHECK (EMAIL_VERIFIED      IN (0,1))
) IN DEMOTBS;

-- =============================================================================
-- ADDRESSES
-- =============================================================================

CREATE TABLE ADDRESSES (
    ID             BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    ADDRESS_LINE1  VARCHAR(255),
    ADDRESS_LINE2  VARCHAR(255),
    ADDRESS_TYPE   VARCHAR(255),
    CITY           VARCHAR(255),
    STATE          VARCHAR(255),
    POSTAL_CODE    VARCHAR(255),
    COUNTRY        VARCHAR(255),
    CUSTOMER_ID    BIGINT,
    IS_DEFAULT     SMALLINT DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT CK_ADDR_IS_DEFAULT CHECK (IS_DEFAULT IN (0,1)),
    CONSTRAINT FK_ADDRESSES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
) IN DEMOTBS;

-- =============================================================================
-- LISTINGS (replaces OFFERS; holds inventory)
-- =============================================================================

CREATE TABLE LISTINGS (
    ID              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    BOOK_ID         BIGINT NOT NULL,
    SELLER_ID       BIGINT NOT NULL,
    PRICE           DECIMAL(31,2) NOT NULL,
    QUANTITY        INTEGER DEFAULT 1 NOT NULL,
    CONDITION_ID    BIGINT,
    STATUS          INTEGER DEFAULT 0 NOT NULL,
    LISTING_TYPE    VARCHAR(20) NOT NULL,
    ADMIN_NOTES     VARCHAR(1000),
    PROCESSED_AT    TIMESTAMP(6),
    PROCESSED_BY    BIGINT,
    IS_FEATURED     SMALLINT DEFAULT 0,
    IS_BESTSELLER   SMALLINT DEFAULT 0,
    IS_NEW_ARRIVAL  SMALLINT DEFAULT 0,
    CREATED_ON      TIMESTAMP(6) NOT NULL,
    UPDATED_ON      TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT CK_LIST_FEATURED    CHECK (IS_FEATURED    IN (0,1)),
    CONSTRAINT CK_LIST_BESTSELLER  CHECK (IS_BESTSELLER  IN (0,1)),
    CONSTRAINT CK_LIST_NEW_ARRIVAL CHECK (IS_NEW_ARRIVAL IN (0,1)),
    CONSTRAINT FK_LISTINGS_BOOK         FOREIGN KEY (BOOK_ID)      REFERENCES BOOKS (ID),
    CONSTRAINT FK_LISTINGS_SELLER       FOREIGN KEY (SELLER_ID)    REFERENCES CUSTOMERS (ID),
    CONSTRAINT FK_LISTINGS_CONDITION    FOREIGN KEY (CONDITION_ID) REFERENCES CONDITIONS (ID),
    CONSTRAINT FK_LISTINGS_PROCESSED_BY FOREIGN KEY (PROCESSED_BY) REFERENCES CUSTOMERS (ID)
) IN DEMOTBS;

-- =============================================================================
-- ORDERS
-- =============================================================================
-- The Oracle original declares NO foreign keys on ORDERS despite having
-- CUSTOMER_ID and ADDRESS_ID. That omission is preserved deliberately so the
-- converted schema is behaviourally identical -- adding the FKs here would
-- change what the demo data and the archive_old_orders procedure can do.

CREATE TABLE ORDERS (
    ID                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CUSTOMER_ID         BIGINT,
    ADDRESS_ID          BIGINT,
    CREATED_ON          TIMESTAMP(6) NOT NULL,
    UPDATED_ON          TIMESTAMP(6),
    STATUS              VARCHAR(255),
    TOTAL_AMOUNT        DECIMAL(31,2),
    DISCOUNT            DECIMAL(31,2),
    TAX                 DECIMAL(31,2),
    SHIPPING_COST       DECIMAL(31,2),
    PAYMENT_METHOD      VARCHAR(255),
    PAYMENT_STATUS      VARCHAR(255),
    SHIPPED_DATE        DATE,
    DELIVERED_DATE      DATE,
    CANCELLED_DATE      DATE,
    CANCELLATION_REASON VARCHAR(255),
    TRACKING_NUMBER     VARCHAR(255),
    NOTES               VARCHAR(1000),
    PRIMARY KEY (ID)
) IN DEMOTBS;

-- =============================================================================
-- ORDER_ITEMS
-- =============================================================================

CREATE TABLE ORDER_ITEMS (
    ID          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    ORDER_ID    BIGINT,
    BOOK_ID     BIGINT,
    LISTING_ID  BIGINT,
    QUANTITY    INTEGER NOT NULL,
    BOOK_PRICE  DECIMAL(31,2) NOT NULL,
    DISCOUNT    DECIMAL(31,2),
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ITEMS_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS (ID),
    CONSTRAINT FK_ORDER_ITEMS_BOOK    FOREIGN KEY (BOOK_ID)    REFERENCES BOOKS (ID),
    CONSTRAINT FK_ORDER_ITEMS_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS (ID)
) IN DEMOTBS;

-- =============================================================================
-- SHOPPING_CART_ITEMS
-- =============================================================================

CREATE TABLE SHOPPING_CART_ITEMS (
    ID                BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    CUSTOMER_ID       BIGINT,
    BOOK_ID           BIGINT,
    LISTING_ID        BIGINT,
    QUANTITY          INTEGER,
    IS_WISHLIST_ITEM  SMALLINT DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT CK_CART_IS_WISHLIST CHECK (IS_WISHLIST_ITEM IN (0,1)),
    CONSTRAINT FK_CART_ITEMS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
    CONSTRAINT FK_CART_ITEMS_BOOK     FOREIGN KEY (BOOK_ID)     REFERENCES BOOKS (ID),
    CONSTRAINT FK_CART_ITEMS_LISTING  FOREIGN KEY (LISTING_ID)  REFERENCES LISTINGS (ID)
) IN DEMOTBS;

-- =============================================================================
-- PASSWORD_RESET_TOKENS
-- =============================================================================
-- "USED" is not a Db2 reserved word; kept as-is.

CREATE TABLE PASSWORD_RESET_TOKENS (
    ID           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE),
    TOKEN        VARCHAR(255),
    CUSTOMER_ID  BIGINT,
    EXPIRY_DATE  TIMESTAMP(6),
    USED         SMALLINT DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT CK_PWRESET_USED CHECK (USED IN (0,1)),
    CONSTRAINT FK_PASSWORD_RESET_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
) IN DEMOTBS;

-- =============================================================================
-- PERSISTENT_LOGINS (Spring Security "remember me")
-- =============================================================================

CREATE TABLE PERSISTENT_LOGINS (
    USERNAME   VARCHAR(64) NOT NULL,
    SERIES     VARCHAR(64) NOT NULL,
    TOKEN      VARCHAR(64) NOT NULL,
    LAST_USED  TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (SERIES)
) IN DEMOTBS;

-- =============================================================================
-- INDEXES
-- =============================================================================
-- Direct 1:1 conversions; Db2 CREATE INDEX syntax matches Oracle's here.

CREATE INDEX IDX_BOOKS_SEARCH    ON BOOKS(SEARCH_TEXT);
CREATE INDEX IDX_BOOKS_ISBN      ON BOOKS(ISBN);
CREATE INDEX IDX_BOOKS_GENRE     ON BOOKS(GENRE_ID);
CREATE INDEX IDX_BOOKS_PUBLISHER ON BOOKS(PUBLISHER_ID);

CREATE INDEX IDX_LISTINGS_STATUS      ON LISTINGS(STATUS);
CREATE INDEX IDX_LISTINGS_SELLER      ON LISTINGS(SELLER_ID);
CREATE INDEX IDX_LISTINGS_BOOK        ON LISTINGS(BOOK_ID);
CREATE INDEX IDX_LISTINGS_TYPE        ON LISTINGS(LISTING_TYPE);
CREATE INDEX IDX_LISTINGS_TYPE_STATUS ON LISTINGS(LISTING_TYPE, STATUS);

CREATE INDEX IDX_ORDERS_CUSTOMER   ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_STATUS     ON ORDERS(STATUS);
CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_CART_CUSTOMER     ON SHOPPING_CART_ITEMS(CUSTOMER_ID);

-- =============================================================================
-- SEARCH_TEXT MAINTENANCE TRIGGER
-- =============================================================================
-- Oracle original:
--     CREATE OR REPLACE TRIGGER trg_book_search_text
--     BEFORE INSERT OR UPDATE OF TITLE, AUTHOR, ISBN ON BOOKS
--     FOR EACH ROW
--     BEGIN
--       :NEW.SEARCH_TEXT := LOWER(:NEW.TITLE) || ' ' ||
--                           LOWER(NVL(:NEW.AUTHOR,'')) || ' ' ||
--                           LOWER(NVL(:NEW.ISBN,''));
--     END;
--
-- THREE Db2 differences, all of them load-bearing:
--
--  1. Db2 has no "BEFORE INSERT OR UPDATE" -- one trigger per event. Split into
--     two triggers with identical bodies.
--  2. :NEW.col becomes a REFERENCING NEW AS n correlation, assigned with
--     SET n.col = ... inside a compound body. Db2 permits assignment to the
--     new-row correlation only in a BEFORE trigger, which is what we have.
--  3. *** NULL CONCATENATION *** Oracle treats NULL as the empty string in ||,
--     so a NULL TITLE yields ' author isbn'. Db2 propagates NULL, so the same
--     row would set SEARCH_TEXT = NULL and silently disappear from search
--     results. TITLE is therefore wrapped in COALESCE as well -- the Oracle
--     original only wrapped AUTHOR and ISBN, which was a latent bug there and
--     a real one here.

CREATE OR REPLACE TRIGGER TRG_BOOK_SEARCH_TEXT_INS
    NO CASCADE BEFORE INSERT ON BOOKS
    REFERENCING NEW AS N
    FOR EACH ROW
    MODE DB2SQL
    SET N.SEARCH_TEXT = LOWER(COALESCE(N.TITLE,  '')) || ' ' ||
                        LOWER(COALESCE(N.AUTHOR, '')) || ' ' ||
                        LOWER(COALESCE(N.ISBN,   ''));

CREATE OR REPLACE TRIGGER TRG_BOOK_SEARCH_TEXT_UPD
    NO CASCADE BEFORE UPDATE OF TITLE, AUTHOR, ISBN ON BOOKS
    REFERENCING NEW AS N
    FOR EACH ROW
    MODE DB2SQL
    SET N.SEARCH_TEXT = LOWER(COALESCE(N.TITLE,  '')) || ' ' ||
                        LOWER(COALESCE(N.AUTHOR, '')) || ' ' ||
                        LOWER(COALESCE(N.ISBN,   ''));

-- =============================================================================
-- FULL-TEXT INDEX -- NOT CONVERTED
-- =============================================================================
-- Oracle original:
--     CREATE INDEX BOOKS_TEXT_IDX ON BOOKS(SEARCH_TEXT)
--     INDEXTYPE IS CTXSYS.CONTEXT
--     PARAMETERS ('SYNC (ON COMMIT)');
--
-- There is NO Db2 LUW equivalent available here:
--   * Db2 Text Search (CREATE INDEX ... FOR TEXT, via SYSTS_ADMIN_CMD) is a
--     separately installed and licensed component. It is NOT available on
--     Amazon RDS for Db2, and it is not enabled in a default LUW install.
--   * Net Search Extender is withdrawn.
--
-- Consequence for query rewriting: Oracle CONTAINS(SEARCH_TEXT, :q) > 0 and
-- SCORE(1) have no direct replacement. The portable substitute is a LIKE
-- predicate over the same SEARCH_TEXT column, which the plain B-tree index
-- IDX_BOOKS_SEARCH above can support for prefix matches (LIKE 'foo%') but not
-- for infix matches (LIKE '%foo%', which forces a scan). Relevance ranking is
-- lost entirely. This is the same substitution made in the application's
-- BookRepository.fullTextSearchBooks.
--
-- If ranked full-text search is a hard requirement, the options are Db2 Text
-- Search on self-managed LUW, or externalising search to OpenSearch.
-- =============================================================================

COMMIT;

CONNECT RESET;

-- =============================================================================
-- Verify: expect 14 tables, 13 indexes (plus PK indexes), 2 triggers
-- =============================================================================
-- SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA='DEMO' AND TYPE='T' ORDER BY 1;
-- SELECT INDNAME FROM SYSCAT.INDEXES WHERE TABSCHEMA='DEMO' AND UNIQUERULE='D' ORDER BY 1;
-- SELECT TRIGNAME FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA='DEMO' ORDER BY 1;
