-- =============================================================================
-- Bob's Used Books workshop - Db2 LUW data reload
-- Converted from reload_data.sql (Oracle)
-- =============================================================================
-- Empties every table and resets the identity generators, so that
-- 03_data_db2_v2.sql can be re-run and produce the same IDs as a fresh load
-- (Admin=1, John Doe=2, Jane Doe=3).
--
-- DESTRUCTIVE. Deletes all rows in schema DEMO. It does not drop objects --
-- for that use demo_cleanup_db2.sql.
--
-- ORACLE -> DB2 MAPPING
--   ALTER TABLE t MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART)
--       -> ALTER TABLE t ALTER COLUMN ID RESTART WITH 1
--          Db2 does not re-specify the identity clause to reset it; RESTART
--          WITH is a standalone column alteration.
--   @src/main/resources/db/oracle/data_oracle_jpa_v2.sql   (sqlplus include)
--       -> no Db2 CLP equivalent. Run the data script as a separate command;
--          see the bottom of this file.
--
-- TWO CORRECTIONS TO THE ORACLE ORIGINAL
--
--   1. DELETE ORDER. The Oracle script deleted BOOKS before BOOKS_COVER, but
--      BOOKS_COVER has a FK to BOOKS. That only worked because the FK is
--      ON DELETE CASCADE, so deleting BOOKS silently emptied BOOKS_COVER and
--      the trailing "DELETE FROM books_cover" was a no-op. Db2 behaves the same
--      way, but relying on it is fragile, so BOOKS_COVER is deleted explicitly
--      first and the order is otherwise strictly child-before-parent.
--
--   2. MISSING TABLES. The Oracle script never cleared PASSWORD_RESET_TOKENS
--      (which has a FK to CUSTOMERS) or PERSISTENT_LOGINS. A row in
--      PASSWORD_RESET_TOKENS would make the CUSTOMERS delete fail with a
--      constraint violation. Both are included below.
--
-- Run as DEMO:  db2 -tvf reload_data_db2.sql
--
-- PLACEHOLDER: the CONNECT below uses <DEMO_PASSWORD>, not a real password.
-- This script is NOT run by the one-click stack, so nothing substitutes it for
-- you. Before running interactively, either replace the placeholder with the
-- DEMO password or drop the CONNECT line and connect first:
--   db2 connect to BOBSDB user DEMO using "$DEMO_PASSWORD"
-- =============================================================================

CONNECT TO BOBSDB USER DEMO USING <DEMO_PASSWORD>;
SET CURRENT SCHEMA DEMO;

-- -----------------------------------------------------------------------------
-- Delete all data, children before parents
-- -----------------------------------------------------------------------------
DELETE FROM SHOPPING_CART_ITEMS;
DELETE FROM ORDER_ITEMS;
DELETE FROM ORDERS;
DELETE FROM PASSWORD_RESET_TOKENS;
DELETE FROM PERSISTENT_LOGINS;
DELETE FROM LISTINGS;
DELETE FROM ADDRESSES;
DELETE FROM BOOKS_COVER;
DELETE FROM BOOKS;
DELETE FROM CUSTOMERS;
DELETE FROM PUBLISHERS;
DELETE FROM GENRES;
DELETE FROM BOOK_TYPES;
DELETE FROM CONDITIONS;

COMMIT;

-- -----------------------------------------------------------------------------
-- Reset identity generators to 1
-- -----------------------------------------------------------------------------
-- Oracle: ALTER TABLE t MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART)
ALTER TABLE CUSTOMERS             ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ADDRESSES             ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE GENRES                ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE PUBLISHERS            ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BOOK_TYPES            ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE CONDITIONS            ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BOOKS                 ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LISTINGS              ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ORDERS                ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ORDER_ITEMS           ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SHOPPING_CART_ITEMS   ALTER COLUMN ID RESTART WITH 1;
-- Not in the Oracle original, but needed for a complete reset:
ALTER TABLE PASSWORD_RESET_TOKENS ALTER COLUMN ID RESTART WITH 1;
-- (BOOKS_COVER.BOOK_ID and PERSISTENT_LOGINS.SERIES are not identity columns.)

COMMIT;

-- -----------------------------------------------------------------------------
-- Verify empty
-- -----------------------------------------------------------------------------
SELECT 'customers'   AS T, COUNT(*) AS N FROM CUSTOMERS
UNION ALL SELECT 'books',       COUNT(*) FROM BOOKS
UNION ALL SELECT 'books_cover', COUNT(*) FROM BOOKS_COVER
UNION ALL SELECT 'listings',    COUNT(*) FROM LISTINGS
UNION ALL SELECT 'orders',      COUNT(*) FROM ORDERS;

CONNECT RESET;

-- =============================================================================
-- Now load the data
-- =============================================================================
-- The Oracle script ended with the sqlplus include directive
--     @src/main/resources/db/oracle/data_oracle_jpa_v2.sql
-- The Db2 CLP has no equivalent, so run the data script yourself:
--
--     db2 -tvf 03_data_db2_v2.sql
--
-- Or chain both in one shell command:
--
--     db2 -tvf reload_data_db2.sql && db2 -tvf 03_data_db2_v2.sql
-- =============================================================================
