-- =============================================================================
-- Knowledge base entries for Db2 LUW -> PostgreSQL migrations
-- =============================================================================
-- V3 seeded 12 entries covering oracle, sqlserver and sybase sources. Db2 was
-- absent, so with a Db2 source every KnowledgeBaseRepository lookup returned
-- nothing (the queries filter on kb.sourceDbEngine = :sourceDbEngine) and the
-- Kiro agent generated tests with no conversion guidance.
--
-- A separate migration rather than an edit to V3: Flyway records V3 as applied,
-- so changing it would not re-run and would break the checksum on existing
-- databases.
--
-- Engine value is 'db2', matching DatabaseEndpointService.normalizeEngine and
-- the "engine" field in the Db2 admin secret.
--
-- Priorities follow V3: 20 = DDL conversion, 15 = test-data guidance,
-- 10 = procedure testing.
-- =============================================================================

INSERT INTO knowledge_bases (name, description, source_db_engine, target_db_engine, content, active, priority, created_at, updated_at)
VALUES 
(
    'Db2 LUW to PostgreSQL DDL Conversion Best Practices',
    'General guidelines for converting Db2 LUW DDL to PostgreSQL',
    'db2',
    'postgres',
    'Best Practices for Db2 LUW to PostgreSQL DDL Conversion:

1. Data Type Mappings:
   - SMALLINT → SMALLINT
   - INTEGER/INT → INTEGER
   - BIGINT → BIGINT
   - DECIMAL(p,s)/NUMERIC(p,s) → NUMERIC(p,s)
   - DECIMAL(31,2) → NUMERIC(31,2) (Db2 max precision is 31, PostgreSQL allows more)
   - DECFLOAT → NUMERIC (no direct equivalent; DECFLOAT(16|34) is IEEE decimal)
   - REAL → REAL
   - DOUBLE/FLOAT → DOUBLE PRECISION
   - CHAR(n) → CHAR(n)
   - VARCHAR(n) → VARCHAR(n)
   - CLOB(n) → TEXT
   - GRAPHIC/VARGRAPHIC/DBCLOB → CHAR/VARCHAR/TEXT (PostgreSQL is UTF-8 native)
   - BLOB(n) → BYTEA (Db2 requires an explicit maximum, e.g. BLOB(10M); BYTEA does not)
   - DATE → DATE
   - TIME → TIME
   - TIMESTAMP(p) → TIMESTAMP(p) (Db2 default precision is 6, same as PostgreSQL)
   - XML → XML
   - BOOLEAN → BOOLEAN
   - ROWID → no equivalent; use a surrogate key

2. Identity and Sequences:
   - GENERATED BY DEFAULT AS IDENTITY → GENERATED BY DEFAULT AS IDENTITY (PG 10+)
   - GENERATED ALWAYS AS IDENTITY → GENERATED ALWAYS AS IDENTITY
   - Db2 (START WITH n INCREMENT BY n NO CYCLE) maps directly
   - ALTER TABLE t ALTER COLUMN c RESTART WITH n
       → ALTER TABLE t ALTER COLUMN c RESTART WITH n
   - NEXT VALUE FOR seq → nextval(''seq'')
   - PREVIOUS VALUE FOR seq → currval(''seq'')

3. Syntax Conversions:
   - CURRENT DATE / CURRENT TIME / CURRENT TIMESTAMP → CURRENT_DATE / CURRENT_TIME / CURRENT_TIMESTAMP
   - VALUES expr (as a statement) → SELECT expr
   - SELECT ... FROM SYSIBM.SYSDUMMY1 → SELECT ... (PostgreSQL needs no dummy table)
   - FETCH FIRST n ROWS ONLY → LIMIT n (or FETCH FIRST n ROWS ONLY, also valid in PG)
   - COALESCE/VALUE(a, b) → COALESCE(a, b)
   - NVL(a, b) → COALESCE(a, b)
   - LENGTH() → LENGTH() (for characters) / OCTET_LENGTH() (for bytes)
   - POSSTR(str, sub) / LOCATE(sub, str) → POSITION(sub IN str)
   - SUBSTR(str, start, len) → SUBSTRING(str FROM start FOR len)
   - str1 CONCAT str2 or str1 || str2 → str1 || str2
   - DAYS(d1) - DAYS(d2) → d1 - d2 (integer days)
   - d + n DAYS → d + n * INTERVAL ''1 day''
   - TIMESTAMP_FORMAT(s, fmt) → TO_TIMESTAMP(s, fmt)
   - VARCHAR_FORMAT(ts, fmt) → TO_CHAR(ts, fmt)
   - CAST(x AS type) → CAST(x AS type)
   - RAISE_ERROR(sqlstate, text) → RAISE EXCEPTION USING ERRCODE = sqlstate

4. Catalog Views (Db2 has no dba_*/all_* views):
   - SYSCAT.TABLES → information_schema.tables / pg_class
   - SYSCAT.COLUMNS → information_schema.columns
   - SYSCAT.INDEXES + SYSCAT.INDEXCOLUSE → pg_indexes
   - SYSCAT.ROUTINES → information_schema.routines
   - SYSCAT.TRIGGERS → information_schema.triggers
   - SYSCAT.REFERENCES → information_schema.referential_constraints
   - SYSCAT.SEQUENCES → information_schema.sequences
   NOTE: on RDS for Db2, a non-administrative user may have no SELECT on SYSCAT.
   The master user does. Queries against SYSCAT fail with SQLCODE=-551
   (SQLSTATE 42501) for users without that privilege.

5. Routines and Packages:
   - Db2 has CREATE MODULE, but Oracle-style packages are usually flattened:
     pkg.routine → PKG_ROUTINE. Keep the naming consistent so callers resolve.
   - CREATE PROCEDURE p(...) LANGUAGE SQL BEGIN ... END
       → CREATE OR REPLACE PROCEDURE p(...) LANGUAGE plpgsql AS $$ BEGIN ... END; $$
   - Scalar function: BEGIN RETURN expr; END is valid in Db2 and maps to plpgsql.
   - TABLE function: a Db2 SQL table function body is a BARE `RETURN <select>`
     directly after the options, NOT wrapped in BEGIN ... END. Wrapping it fails
     with SQLCODE=-104 (SQLSTATE 42601), because a compound statement can only
     return a scalar. In PostgreSQL the equivalent is
     RETURNS TABLE(...) ... AS $$ BEGIN RETURN QUERY SELECT ...; END; $$
   - Db2 functions have no parameter defaults. A defaulted Oracle argument is
     commonly expressed as a 0-argument overload; PostgreSQL supports DEFAULT
     directly, so overloads can be collapsed back.
   - Error signalling: Db2 uses SIGNAL SQLSTATE ''75001'' SET MESSAGE_TEXT = ...
       → RAISE EXCEPTION ''...'' USING ERRCODE = ''75001''

6. Statement Terminators in Scripts:
   - Routine bodies contain inner semicolons, so scripts declare an alternative
     terminator: --#SET TERMINATOR # ... then END#
   - Strip these directives when converting; PostgreSQL uses $$ quoting instead.

7. Connection Statements:
   - CONNECT TO db USER u USING p / CONNECT RESET are CLP-only and have no JDBC
     equivalent. Remove them; the connection comes from the JDBC URL.

8. RDS for Db2 Specifics (source side):
   - CREATE BUFFERPOOL / CREATE TABLESPACE are unavailable to the master user
     (no SYSADM/SYSCTRL). Use rdsadmin.create_tablespace and related procedures,
     which only resolve while connected to the RDSADMIN database.
   - Users are database-authenticated via rdsadmin.add_user, not OS users.
   - SYSPROC.ADMIN_CMD (used for RUNSTATS, REORG) is not executable by ordinary
     users; the ROLE_PROCEDURES role covers SYSIBM, not SYSPROC.',
    TRUE,
    20,
    NOW(),
    NOW()
)
ON CONFLICT DO NOTHING;

INSERT INTO knowledge_base_categories (knowledge_base_id, category) 
SELECT id, cat FROM knowledge_bases, (VALUES ('DDL_CONVERSION')) AS t(cat)
WHERE name = 'Db2 LUW to PostgreSQL DDL Conversion Best Practices'
ON CONFLICT DO NOTHING;


INSERT INTO knowledge_bases (name, description, source_db_engine, target_db_engine, content, active, priority, created_at, updated_at)
VALUES 
(
    'Use MCP Servers for Realistic Test Data - Db2 to PostgreSQL',
    'Guidelines for using MCP servers to query actual Db2 LUW and PostgreSQL database values for test cases',
    'db2',
    'postgres',
    'MCP Server Integration for Test Case Generation:

1. Access to Database Connections:
   - Use db2-luw-client-mcp to query the source Db2 LUW database
   - Use postgres-client-mcp to query the target PostgreSQL database
   - Retrieve actual data values to make test cases more realistic and relevant

2. Test Data Strategy:
   - For UPDATE/DELETE operations: Query existing records to use actual IDs/keys that exist in the database
   - For SELECT operations: Use actual filter values that return real data
   - For INSERT operations: Check existing data to avoid constraint violations

3. Happy Path Test Cases:
   - Query sample records from relevant tables to use as test inputs
   - Ensure test values match actual data types and constraints
   - Use real foreign key values that exist in parent tables

4. Example Queries (Db2 LUW):
   - SELECT a few sample IDs: SELECT ID FROM SCHEMA.TABLE FETCH FIRST 3 ROWS ONLY
   - Get valid foreign keys: SELECT DISTINCT FK_COLUMN FROM SCHEMA.TABLE WHERE FK_COLUMN IS NOT NULL FETCH FIRST 5 ROWS ONLY
   - Check data ranges: SELECT MIN(COLUMN), MAX(COLUMN) FROM SCHEMA.TABLE
   - Row counts: SELECT COUNT(*) FROM SCHEMA.TABLE
   - Scalar expression without a table: VALUES CURRENT TIMESTAMP
     (or SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1)

5. Db2 Identifier Casing:
   - Unquoted identifiers fold to UPPERCASE in Db2, so schema, table and column
     names are typically DEMO.BOOKS.TITLE
   - DMS Schema Conversion here applies convert-lowercase, so the PostgreSQL
     target is demo.books.title
   - Use the correct case for each side; a lowercase Db2 query fails with
     SQLCODE=-204 (undefined name)

6. LOB Columns:
   - Db2 BLOB/CLOB columns require an explicit maximum length (e.g. BLOB(10M))
   - Avoid SELECT * on tables with large LOBs when sampling; project the columns
     needed, or use LENGTH(lob_column) to check size without transferring data

7. Benefits:
   - Tests are more realistic and meaningful
   - Reduces false failures from non-existent test data
   - Validates actual database state and constraints',
    TRUE,
    15,
    NOW(),
    NOW()
)
ON CONFLICT DO NOTHING;

INSERT INTO knowledge_base_categories (knowledge_base_id, category) 
SELECT id, cat FROM knowledge_bases, (VALUES ('UNIT_TEST'), ('COMPARISON_TEST')) AS t(cat)
WHERE name = 'Use MCP Servers for Realistic Test Data - Db2 to PostgreSQL'
ON CONFLICT DO NOTHING;


INSERT INTO knowledge_bases (name, description, source_db_engine, target_db_engine, content, active, priority, created_at, updated_at)
VALUES 
(
    'Procedure Testing with Transaction Rollback - Db2 to PostgreSQL',
    'Test stored procedures by querying data before/after execution with rollback to preserve data integrity',
    'db2',
    'postgres',
    'Procedure Testing Strategy with Transaction Rollback:

1. Test Pattern for Data-Modifying Procedures:
   - Query relevant tables BEFORE procedure execution to capture initial state
   - Execute the procedure being tested
   - Query the same tables AFTER procedure execution to verify changes
   - ROLLBACK the transaction to restore the original data state

2. Db2 LUW Syntax for Testing:
   a) Simple query-execute-query pattern:
      SELECT COUNT(*) AS BEFORE_COUNT FROM SCHEMA.TABLE WHERE CONDITION;
      CALL SCHEMA.PROCEDURE_NAME(value1, value2);
      SELECT COUNT(*) AS AFTER_COUNT FROM SCHEMA.TABLE WHERE CONDITION;
      ROLLBACK;

   b) Reading OUT parameters:
      Db2 CALL returns OUT parameters to the client rather than into session
      variables, so capture them from the CALL result set. Over JDBC use
      CallableStatement with registerOutParameter.

   c) CRITICAL: Db2 LUW syntax rules:
      - Use CALL for procedure invocation (there is no EXEC)
      - Autocommit is ON by default over JDBC/CLP: disable it before the test,
        or the ROLLBACK has nothing to undo
        (JDBC: conn.setAutoCommit(false); CLP: UPDATE COMMAND OPTIONS USING C OFF)
      - Parameters are positional: CALL p(1, ''x'') - there is no @name = value form
      - Variables exist only inside a compound block (BEGIN ... END), not at
        statement level
      - Statements terminate with ; unless the script sets an alternative
        terminator via --#SET TERMINATOR

3. PostgreSQL Syntax for Testing:
   BEGIN;
   SELECT COUNT(*) AS before_count FROM schema.table WHERE condition;
   CALL schema.procedure_name(param1, param2);
   SELECT COUNT(*) AS after_count FROM schema.table WHERE condition;
   ROLLBACK;

4. Implementation Steps:
   a) Use the MCP server to query the initial data state
   b) Execute the procedure with test parameters
   c) Query the data again to verify the procedure effects
   d) ROLLBACK to undo all changes

5. Behaviour Differences to Watch:
   - A Db2 procedure that issues its own COMMIT makes the outer ROLLBACK a
     no-op; check the body before relying on rollback isolation
   - Db2 error signalling uses SIGNAL SQLSTATE ''75001''; PostgreSQL raises
     RAISE EXCEPTION ... USING ERRCODE = ''75001''. Compare SQLSTATE values
     rather than vendor error numbers
   - A Db2 function cannot perform INSERT/UPDATE/DELETE, so an Oracle function
     that modified data is commonly converted to a PROCEDURE with an OUT
     parameter. Test it as a procedure, not a function

6. Benefits:
   - Validates procedure logic without data corruption
   - Enables repeatable testing on production-like data
   - Verifies actual database impact, not just return values
   - Safe for testing in shared environments',
    TRUE,
    10,
    NOW(),
    NOW()
)
ON CONFLICT DO NOTHING;

INSERT INTO knowledge_base_categories (knowledge_base_id, category) 
SELECT id, cat FROM knowledge_bases, (VALUES ('UNIT_TEST'), ('COMPARISON_TEST')) AS t(cat)
WHERE name = 'Procedure Testing with Transaction Rollback - Db2 to PostgreSQL'
ON CONFLICT DO NOTHING;
